/**
 * The demo samples.
 *
 * `public/samples/index.json` is generated by Codex's `scripts/make_demo_samples.py`
 * and never hand-edited. Every sample is a stored result of a real pipeline run
 * on a made-up letter, so the source badge -- not this list -- says how each
 * result was produced. If the manifest is missing or malformed, the Meridian
 * sample alone is offered, exactly as before the manifest existed.
 */

import { useEffect, useState } from "react";
import { z } from "zod";

export const SampleEntry = z.object({
  slug: z.string().regex(/^[a-z0-9_-]+$/),
  title: z.string(),
  layout: z.string(),
  note: z.string(),
  pdf: z.string().startsWith("/"),
  json: z.string().startsWith("/"),
});
export type SampleEntry = z.infer<typeof SampleEntry>;

export const DEFAULT_SAMPLE: SampleEntry = {
  slug: "meridian",
  title: "Meridian State University",
  layout: "Two-page award letter",
  note: "A conventional offer whose merit scholarship has an unresolved period.",
  pdf: "/sample_offer.pdf",
  json: "/sample_offer.json",
};

export async function fetchSamples(): Promise<SampleEntry[]> {
  try {
    const response = await fetch("/samples/index.json");
    if (!response.ok) return [DEFAULT_SAMPLE];
    const list = z.array(SampleEntry).min(1).parse(await response.json());
    return list;
  } catch {
    return [DEFAULT_SAMPLE];
  }
}

/** The sample list for links; starts with Meridian so nothing flickers. */
export function useSamples(): SampleEntry[] {
  const [samples, setSamples] = useState<SampleEntry[]>([DEFAULT_SAMPLE]);
  useEffect(() => {
    let cancelled = false;
    void fetchSamples().then((list) => !cancelled && setSamples(list));
    return () => {
      cancelled = true;
    };
  }, []);
  return samples;
}

export function sampleHref(slug: string): string {
  return slug === DEFAULT_SAMPLE.slug ? "/analyze?sample" : `/analyze?sample=${slug}`;
}
